# Generated by Django 4.2.4 on 2023-08-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новость #XXX', max_length=64, verbose_name='Название')),
                ('anons', models.CharField(default='Анонс #XXX', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(default='Статья #XXX', verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
